### ISSUE TITLE
Add meta tags using SEO Keywords

### ISSUE THREAD

**Issue by RevantCI** [Bridgeconn/VachanOnline-v2#561]
Use the Keywords as per the SEO report and add meta tags to the index.html page

[VO Report .pdf](https://github.com/Bridgeconn/VachanOnline-v2/files/14096015/VO.Report.pdf)

**Comment by Beenamol** [comment]
- [ ] Read about meta tags (2 Hours)
- [ ] Read About keywords SEO (2 Hours)
- [ ] Read SEO Reports (2 Hours)
- [ ] Add the keywords in the meta tags in index.html (2 Hours)
- [ ] Code Review ()
- [ ] Code Review Changes ()

**Comment by RevantCI** [comment]
## Keywords
| Keyword | Avg. Search Volume (Last 12 months) |
|--------|--------|
| bible verse of the day | 495000 |
| bible verses | 951000 |
| holy bible | 162000 |
| bible study | 73000 |
| tamil bible | 69000 | 
| telugu bible | 59700 |
| bible kjv online | 22000 |
| audio bible | 34500 |
| online bible | 60000 | 

## Potential Keywords
| Keyword | Avg. Search Volume(Last 12 months) |
|--------|--------|
| sign language bible | 880 |
| read bible online | 9.9k |
| bible animations | 1.0k |
| bible videos | 3.6k |

**Comment by VineethaVi** [comment]
**Steps followed for testing:**

- The staging link was accessed	
- Upon reaching the landing page, the right mouse button was clicked	
- The option to view the page source was selected	
- After selecting the line wrap, the meta keywords were observed 

**Observation:** 
The keywords in the Github issue matched  those in the source code for the page

**Note:** There is further testing to be done at the production site.
