### ISSUE TITLE
Use react-helmet package to add meta tags on more pages as per component shown

### ISSUE THREAD

**Issue by RevantCI** [Bridgeconn/VachanOnline-v2#594]
Add package - https://www.npmjs.com/package/react-helmet
As per Poojas research on SEO for short term we can use this package to improve SEO 
https://github.com/Bridgeconn/VachanOnline-v2/issues/568#issuecomment-1948043833

**Comment by Poojanavgurukul** [comment]
- [ ] Add Package (0.5 hour)
- [ ] Add the meta tags on all pages (3 hours)
- [ ] unit  testing(1 hour)
- [ ] QA()

**Comment by Poojanavgurukul** [comment]
[excel](https://bridgeconn-my.sharepoint.com/:x:/p/pooja_saini/ETbIu5tbr7xLk32BQ1oAk9sBD18Xcod2jdVO5TOUd1pQYA?e=LPZXBA)

**Comment by SeemaNandihal** [comment]
**Test result:** Pass
**Test steps:**
1. From the landing page access features: Read Bible, Study, Audio Bible, Songs, Bible stories and others
2. In the Study Bible page navigate between Mathew 1, Romans 1 and 1 Timothy 1
3. Right click and inspect the title

**Expected results:**
1. The keyword for title should change as per the book selection
Example: If 1 Timothy 1 is selected, the title should be "1 Timothy  1 - Vachan Online"

**Actual results:**
The titles appear for the selected features.

- Study Bible: Matthew  1 - Vachan Online
- Read Bible: Matthew  1 - Eng-ESV - Vachan Online
- Bible stories: 1. The Creation - Bible Stories
- Songs: ह़ुन ता आई जाओ मसीह़ा - Songs

**Screenshot:**
![Image](https://github.com/Bridgeconn/VachanOnline-v2/assets/109131516/c9dd4c4b-b3d2-4272-9f58-183bae36b334)

Moving this issue to done.
